version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: world
    ports:
      - "3306:3306"
    networks:
      - microwave-network

  app:
    build: .
    container_name: microwave-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - microwave-network

networks:
  microwave-network:
    driver: bridge