version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: world
    ports:
      - "3306:3306"
    networks:
      - microwave-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - microwave-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    networks:
      - microwave-network
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  app:
    build: .
    container_name: microwave-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - kafka
    networks:
      - microwave-network

networks:
  microwave-network:
    driver: bridge